services:
  - type: web
    name: laravel-app
    runtime: docker
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-mysql-host.planetscale.com
      - key: DB_PORT
        value: "3306"
      - key: DB_DATABASE
        value: task
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: sandip@1
